### PR TITLE
Resolve marker preview bugs w/ bar plot map type 

### LINKED ISSUE #326: Map - issues with barplot marker previews
Please check this is still a live issue after #190 is completed (and remove the `question` label).

### Issue 1
The logscale mode for the preview bar marker doesn't seem to be right.

Here are no-logs markers - the preview looks similar to the three map markers:
image

Here are logged markers - now they don't look at all similar:
image

_Originally posted by @bobular in https://github.com/VEuPathDB/web-monorepo/issues/285#issuecomment-1604791616_

### Issue 2
The proportion mode is not working in the bar marker preview since the data for the marker preview is coming from the subsetting service, which does not support `valueSpec: 'proportion'`

### PR DESCRIPTION
**Pull request by jernestmyers**
Resolves #326 

This PR addresses two bugs in marker previews:

### log scale bug
- the map markers receive a `dependentAxisRange` that the marker previews were not receiving
- providing the same `dependentAxisRange` to the marker preview appears to resolve this issue

### proportion mode w/ continuous vars
- in proportion mode, the data was erroneously adding together (in a reduce function) _**proportion**_ values that corresponded to the same overlay label in the same manner that we do for counts values; this resulted in an erroneous number displayed as `totalCount` in the marker preview
- now, we add a `count` property to the data that is used to determine `totalCount` irrespective of the plot mode

### CODE REVIEW

File: packages/libs/components/src/map/ChartMarker.tsx [hunk 1]
```diff
@@ -23,6 +23,7 @@ export interface ChartMarkerProps
   borderWidth?: number;
   data: {
     value: number;
+    count?: number;
```
Comment (bobular) [inline packages/libs/components/src/map/ChartMarker.tsx:26]: It seems a shame to introduce this as an optional prop when our EDA usage depends on it (and requires the `count` prop in the `StandaloneMapMarkersResponse` io-ts type. In MapAnalysis we have to fall back to zero so it compiles:
`          count: (data.count ?? 0) + prevData[index].count,`


Of course adding as optional is the right thing to do for backwards compatibility. But we are only using it in storybook stories and the EDA, so let's see how much would need to be changed if we made it compulsory...  A lot of the storybook code would need `{value: 100, count: 100}` duplication (and the counts would be unused), and then also some changes would be needed in src/lib/core/hooks/mapMarkers.tsx and src/lib/map/analysis/MarkerConfiguration/CategoricalMarkerPreview.tsx

I guess the problem here is that we've converted `StandaloneMapMarkersResponse` data into `xxxMarkerProps` data well before it is used to create markers and _while we still need to do calculations on it_.

It seems like a fudge to add an optional prop to a low level component (in `components`) so that operations in higher level components (`eda`) can work, and that the lower-level component will never use.

So I think the solution should lie purely in the EDA code - but maybe check with @dmfalke because big changes are being made to the marker data code. Merge conflict alert!

If Dave's branch didn't exist, I'd suggest creating the following types - probably in `standaloneMapMarkers.tsx` 

```
interface DonutMarkerPropsWithCounts extends DonutMarkerProps {
  data: DonutMarkerProps['data'] & {
    count: number;
  }[];
}
interface ChartMarkerPropsWithCounts extends ChartMarkerProps {
  data: ChartMarkerProps['data'] & {
    count: number;
  }[];
}
```

And `useStandaloneMapMarkers` would return these types instead of the vanilla versions.

File: packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx [hunk 2]
```diff
@@ -503,25 +513,46 @@ function MapAnalysisImpl(props: ImplProps) {
...
+      const dependentAxisLogScale =
+        activeMarkerConfiguration &&
+        'dependentAxisLogScale' in activeMarkerConfiguration
+          ? activeMarkerConfiguration.dependentAxisLogScale
+          : false;
+      const isPlotModeProportion =
+        activeMarkerConfiguration &&
+        'selectedPlotMode' in activeMarkerConfiguration &&
+        activeMarkerConfiguration.selectedPlotMode === 'proportion';
+      const finalChartMarkerData = isPlotModeProportion
```
Comment (bobular) [inline packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx:538]: There's no real need for this ternary switch statement.  The preview marker will look exactly the same if we divide all the counts by `totalCount` or not. The preview marker has no mouse-overs or numbers/axes displayed so it's really just a matter of coloured pixels.

We could keep this in if it feels better though!

**Review by bobular — COMMENTED** [review]
Works great, but I didn't realise the `count` prop was going to be so problematic.

I've made some comments about how I think the data typing should work. Let me know if you need further clarification. Probably best to discuss with Dave and me in the context of his branch.

File: packages/libs/components/src/map/ChartMarker.tsx (hunk 1 above)
Comment (dmfalke) [reply packages/libs/components/src/map/ChartMarker.tsx:26]: What about combining the marker props in `useStandaloneMarkers`? This could be controlled by an option, maybe `summarizeMarkers: boolean`.

File: packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx (hunk 2 above)
Comment (jernestmyers) [reply packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx]: I went ahead and removed this logic.

File: packages/libs/components/src/map/ChartMarker.tsx (hunk 1 above)
Comment (jernestmyers) [reply packages/libs/components/src/map/ChartMarker.tsx]: I opted for @bobular's approach as it felt more straightforward in my hazy brain!

File: packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx [hunk 3]
```diff
@@ -484,17 +485,26 @@ function MapAnalysisImpl(props: ImplProps) {
     const initialDataObject = previewMarkerData[0].data.map((data) => ({
       label: data.label,
       value: 0,
+      count: 0,
       ...(data.color ? { color: data.color } : {}),
     }));
     const typedData =
       markerType === 'pie'
         ? ([...previewMarkerData] as DonutMarkerProps[])
```
[the remark this answers is not in the document]
Comment (jernestmyers) [reply packages/libs/eda/src/lib/map/analysis/MapAnalysis.tsx]: Good catch!

File: packages/libs/components/src/map/ChartMarker.tsx [hunk 4]
```diff
@@ -315,3 +317,13 @@ function chartMarkerSVGIcon(props: ChartMarkerStandaloneProps): {
     sumValuesString,
   };
 }
+
+export function getChartMarkerDependentAxisRange(
+  data: ChartMarkerProps['data'],
+  isLogScale: boolean
+) {
+  return {
+    min: isLogScale ? 0.1 : 0, // matches what we pass into map markers
```
Comment (bobular) [inline packages/libs/components/src/map/ChartMarker.tsx:326]: 0.1 would be fine as a minimum for count-based dependent axes, but I see that in at least one place (`chartMarkerData` for `continuousMarkerPreview` in MapAnalysis.txt) proportion data is being passed.

So something like this would be safer, in case there are positive values smaller than 0.1.

```
min: isLogScale ? Math.min(0.1, ...data.filter(({value}) => value > 0).map(({value}) => value)) : 0,
```

Comment (bobular) [reply packages/libs/components/src/map/ChartMarker.tsx:326]: In fact, it seems to be an issue with continuous vars...

before:
image

after:
image

Hmm, it's better, but something's still not right. It doesn't look roughly like all the map markers:

image

Comment (bobular) [reply packages/libs/components/src/map/ChartMarker.tsx:326]: OK, it seems like the answer is NOT to do `value: d.count / totalCount,` in MapAnalysis.tsx:L601 

It's fine to pass the regular `dataWithCounts` to `ChartMarkerStandalone` and `getChartMarkerDependentAxisRange`

The maths for the proportions doesn't quite work out properly, but I think it's OK because they look kind of right, and a bit different from the count-based log preview markers, which is desirable, to give some UI feedback when the user changes from counts to proportions (in log mode or not).

Let's look at this again when you've had a chance to have another look.

**Review by bobular — COMMENTED** [review]
Everything looks great - let's just have another look at the minimum thing I pointed out.

File: packages/libs/components/src/map/ChartMarker.tsx (hunk 4 above)
Comment (bobular) [reply packages/libs/components/src/map/ChartMarker.tsx:326]: To be really strict - the "proportion to counts to sum to proportions" is probably necessary but I'm not sure we need to. Let's see how it looks/behaves.

**Review by bobular — APPROVED** [review]
Tested fully and it's looking great.

I properly reviewed the final commit and that looks great too.  I think I had looked at earlier work already so let's call this a wrap!
