### PR TITLE
Ortho ghost overlay fixes

### LINKED ISSUE #1280: Ortho 7 - beta bugs
- [x] Pfam filter button is now a bit crazy (probably related to the change @bobular recently made allowing `ReactNode` rendering
- [x] filters freeze up with multiple pfam filters active (explanation in comment below)

image

### LINKED ISSUE #1370: Ortho 7 - tree/table not always in alignment and associated text filter bug
This is from https://qa.orthomcl.org/orthomcl.b6_22/app/record/group/OG7_0000011#Sequences

Image

Note that there is an additional table entry between the two highlighted leaf nodes.

The `:RNA` in the sequence's `full_id` hasn't been processed properly (everything after the colon is discarded in patristic tree node IDs)

Also if you text-search the table for `:RNA` you get a runtime error!

### PR DESCRIPTION
**Pull request by bobular**
# Ready for review

Resolves https://github.com/VEuPathDB/web-monorepo/issues/1303

Resolves #1280

Resolves #1370 

<s>Implement dynamic Popover transition durations—enter fixed at 300 ms, exit set to Math.max(300, numSequences/10)—so that even with very large groups (e.g. 2.6 s for 26,000 sequences) the popover buttons go away cleanly without leaving behind ghost overlays that block the UI. (Main thread compute was disrupting the animation event processing. The extra animation time effectively waits for the compute to be done.) Groups <= 3,000 proteins won't see any UI behaviour differences at all.</s>

NEW APPROACH: figure out when the component `isFiltering` from `(realState !== volatileState)` and then do several things:
1. grey out the main table and overlay some LOADING text (our default `Loading` spinner doesn't work due to hardcoded 200ms delay)
2. tell the Popover components that they should `deferClosing` while `isFiltering`
   - while Popovers are deferring closing they are greyed out and unclickable

Amazingly it works very nicely.

Filtering logic was also optimized by using Sets for membership checks, ensuring responsive performance on large groups.

Note that the ClinEpi popover behaviour should be unchanged but I need to 

- [x] test ClinEpi

Here is the fix evidence for #1370

image

### CODE REVIEW

File: packages/libs/coreui/src/components/buttons/PopoverButton/PopoverButton.tsx
Comment (bobular) [inline packages/libs/coreui/src/components/buttons/PopoverButton/PopoverButton.tsx:1]: Just prop passing

File: packages/libs/coreui/src/components/inputs/SelectList.tsx [hunk 1]
```diff
@@ -30,31 +37,36 @@ export default function SelectList<T extends string>({
...
   const [selected, setSelected] = useState<SelectListProps<T>['value']>(value);
   const [buttonDisplayContent, setButtonDisplayContent] = useState<ReactNode>(
     getDisplayContent(value, items, defaultButtonDisplayContent)
   );
+  const [isOpen, setIsOpen] = useState(false);
 
-  const onClose = () => {
-    onChange(selected);
+  const onClose = useCallback(() => {
+    if (!instantUpdate) onChange(selected);
```
Comment (bobular) [inline packages/libs/coreui/src/components/inputs/SelectList.tsx:50]: Added this to be symmetrical with `handleCheckboxListUpdate`. No need to update on closing if instant updates were already made. This was probably a harmless oversight.

File: packages/libs/coreui/src/components/inputs/SelectList.tsx [hunk 2]
```diff
@@ -30,31 +37,36 @@ export default function SelectList<T extends string>({
...
+  }, [instantUpdate, selected, items, defaultButtonDisplayContent, onChange]);
 
   /**
    * Keep caller up to date with any selection changes, if required by `instantUpdate`
    */
   const handleCheckboxListUpdate = useCallback(
     (newSelection: SelectListProps<T>['value']) => {
+      // only allow updates while open
+      // seems obvious, but animated transitions blur the lines
+      if (!isOpen) return;
```
Comment (bobular) [inline packages/libs/coreui/src/components/inputs/SelectList.tsx:63]: Here we stop any selection updates being made while the popover is closed. This is possible during animations or when the ghost popover component remains active (but not visible) along with the persistent backdrop.

File: packages/libs/coreui/src/components/inputs/SelectTree/SelectTree.tsx [hunk 3]
```diff
@@ -50,6 +61,15 @@ function SelectTree<T>(props: SelectTreeProps<T>) {
     onSelectionChange(localSelectedList);
   }, [onSelectionChange, localSelectedList]);
 
+  // only used when there's a popover
+  // prevents selections being made while popover is transitioning away
+  const handleUpdateWithPopover = useCallback(
+    (update: string[]) => {
+      if (isPopoverOpen) setLocalSelectedList(update);
```
Comment (bobular) [inline packages/libs/coreui/src/components/inputs/SelectTree/SelectTree.tsx:68]: Same as with SelectList - don't allow selection changes when popover is closed.

File: packages/libs/coreui/src/components/inputs/SelectTree/SelectTree.tsx [hunk 4]
```diff
@@ -94,7 +114,9 @@ function SelectTree<T>(props: SelectTreeProps<T>) {
       customCheckboxes={props.customCheckboxes}
       isMultiPick={props.isMultiPick}
       name={props.name}
-      onSelectionChange={setLocalSelectedList}
+      onSelectionChange={
+        hasPopoverButton ? handleUpdateWithPopover : setLocalSelectedList
+      }
```
Comment (bobular) [inline packages/libs/coreui/src/components/inputs/SelectTree/SelectTree.tsx:119]: We only need the fancy handler when there's a popover button

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.tsx
Comment (bobular) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/components/phyletic-distribution/PhyleticDistributionCheckbox.tsx:1]: Just prop passing

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/RecordTable_TaxonCounts_Filter.tsx
Comment (bobular) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/RecordTable_TaxonCounts_Filter.tsx:1]: More prop passing

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx [hunk 5]
```diff
@@ -97,6 +99,11 @@ export function RecordTable_Sequences(
 
   const numSequences = mesaRows.length;
 
+  const popoverButtonTransitionDuration = {
+    enter: 300,
+    exit: Math.max(300, numSequences / 10),
+  };
+
```
Comment (bobular) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:106]: Here's the dynamic animation time calc.

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx [hunk 6]
```diff
@@ -224,11 +231,16 @@ export function RecordTable_Sequences(
       selectedSpecies.length > 0 ||
       proteinFilterIds.length > 0
     ) {
+      // these two are likely to be selected in large numbers
```
Comment (bobular) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:234]: Below are some filtering performance mods

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx [hunk 7]
```diff
@@ -276,7 +286,8 @@ export function RecordTable_Sequences(
       leaves == null ||
       tree == null ||
       filteredRows == null ||
-      filteredRows.length === 0
+      filteredRows.length === 0 ||
+      filteredRows.length > MAX_SEQUENCES_FOR_TREE
```
Comment (bobular) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:290]: We were filtering the tree even when we're not showing it. Duh! Not any more.

Probably need to add `< MIN_SEQUENCES_FOR_TREE` also.

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx [hunk 8]
```diff
@@ -331,12 +342,17 @@ export function RecordTable_Sequences(
     [mesaColumns]
   );
 
-  const handleSpeciesSelection = useCallback(
-    (species: string[]) => {
-      setSelectedSpecies(species);
+  const handleSpeciesSelection = useCallback((species: string[]) => {
```
Comment (bobular) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:345]: memoised a couple of handlers, just in case (they are hook dependencies downstream)

**Review by bobular — COMMENTED** [review]
Just added a few comments to aid review.

**Review by aurreco-uga — COMMENTED** [review]
i cant reproduce the issue and the fix makes things slower.. but if if we could confirm this is a problem for overseas users i think it is a fine fix..

**Comment by bobular** [comment]
> i cant reproduce the issue and the fix makes things slower.. on big groups. on small groups makes no difference if this is a problem for overseas users i think it is a fine fix..

Thanks @aurreco-uga - actually this isn't a problem related to network speed. It's more to do with client CPU. The slow-down for big groups manifests in the form of slow animations, making it impossible to click quickly between filter buttons, but at least the UI doesn't freeze up completely.

It's not ideal but the only other solution is to use "web workers" which would require a lot more engineering and potentially new bugs.

**Comment by asizemore** [comment]
Code looks good! Will test on Monday!

**Comment by asizemore** [comment]
The tree seemed well-aligned and the funky pfam filter looks all better. The animation to prevent the ghost popover is clever. I had some issues with the popover waiting a few moments before fading out, but i think it's probably better than it was so i'm happy to approve.

**Review by asizemore — APPROVED** [review]
