### PR TITLE
Orthogroup tree table  1254 fixes

### LINKED ISSUE #1254: Ortho 7 - minor UX upgrades
- [x] warning about filtered trees not being same as a tree from filtered protein seqs
- [x] tree/table mismatch warning verbiage and link to contact page, make sure all cases are handled (tree is superset of table not currently caught?)
- [x] Filter should capitalize Core/Peripheral
- [x] See if core/peripheral counts are easy
- [x] Text search instructions are wrong... fixed the search behaviour to match the other tables
- [x] table paging and protein filtering are a bit dodgy. Probably just need to reset to page 1 when applying the protein filter.
- [x] Test `SelectList` button labelling in EDA/MBio (lineplot numerator/denominator, mbio diff abundance condition selectors and elsewhere?)
- [x] Handle excessive "Previous Groups" in header with a "more..." link.

### PR DESCRIPTION
**Pull request by bobular**
Resolves #1254 

I looked into improving the responsiveness of the table paging controls with useDeferredState, but it was not possible due to the memoisation of `mesaState` - which has a mix of "slow" and "volatile" dependencies. I wonder if that memoisation isn't actually necessary? (Answer: I removed it and this reintroduced the janky search field checkboxes...)

### CODE REVIEW

File: packages/libs/coreui/src/components/inputs/SelectList.tsx [hunk 1]
```diff
@@ -15,7 +18,7 @@ export interface SelectListProps<T> extends CheckboxListProps<T> {
   instantUpdate?: boolean;
 }
 
-export default function SelectList<T>({
+export default function SelectList<T extends ReactNode>({
```
Comment (dmfalke) [inline packages/libs/coreui/src/components/inputs/SelectList.tsx:21]: This seems strange to me. `T` is the type of the value. I don't think we ever want that to be a ReactNode. I think we should have `T extends string`, to be honest.

The change you made for `buttonDisplayContent` is perfect.

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx [hunk 2]
```diff
@@ -39,6 +39,10 @@ import {
 import { RecordTable_TaxonCounts_Filter } from './RecordTable_TaxonCounts_Filter';
 import { formatAttributeValue } from '@veupathdb/wdk-client/lib/Utils/ComponentUtils';
 import { RecordFilter } from '@veupathdb/wdk-client/lib/Views/Records/RecordTable/RecordFilter';
+import {
+  areTermsInStringRegexString,
+  parseSearchQueryString,
+} from '../../../../../../../libs/wdk-client/lib/Utils/SearchUtils';
```
Comment (dmfalke) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:45]:
```suggestion
} from '@veupathdb/wdk-client/lib/Utils/SearchUtils';
```

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx [hunk 3]
```diff
@@ -404,7 +408,8 @@ export function RecordTable_Sequences(
   if (
     mesaRows != null &&
     sortedRows != null &&
-    mesaRows.length !== sortedRows.length
+    (mesaRows.length !== sortedRows.length ||
+      mesaRows.length !== leaves?.length)
```
Comment (dmfalke) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:412]: Are both comparisons necessary?

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx [hunk 4]
```diff
@@ -419,8 +424,13 @@ export function RecordTable_Sequences(
       <Banner
         banner={{
           type: 'warning',
-          message:
-            'Tree and protein list mismatch. Please contact the helpdesk',
+          message: (
+            <span>
+              A data processing error has occurred on our end. We apologize for
+              the inconvenience. If this problem persists, please{' '}
+              <Link to="/contact-us">contact us</Link>.
```
Comment (dmfalke) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:431]: Maybe add `target="_blank"`

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx [hunk 5]
```diff
@@ -622,6 +634,22 @@ export function RecordTable_Sequences(
...
+        {MAX_SEQUENCES_FOR_TREE.toLocaleString()} sequences
+      </span>
+    ) : filteredRows.length < sortedRows.length ? (
+      <span>
+        Note: The ortholog group's phylogeny has been pruned to display only the
+        currently filtered proteins. This may differ from a tree constructed{' '}
+        <i>de novo</i> using only these sequences.
+      </span>
+    ) : undefined;
+
```
Comment (dmfalke) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:652]: I have a concern about putting this new message in the same place as the other message. It gets lost. Wouldn't it make more sense to add this to the table description where we describe the ability to filter?

**Review by dmfalke — COMMENTED** [review]
I think this is mostly great. I made several comments, but I don't think any are show stoppers.

File: packages/libs/coreui/src/components/inputs/SelectList.tsx (hunk 1 above)
Comment (bobular) [reply packages/libs/coreui/src/components/inputs/SelectList.tsx:21]: Thanks. I'll try that, but it was my understanding that T needed to be something "compatible with" ReactNode.

Comment (dmfalke) [reply packages/libs/coreui/src/components/inputs/SelectList.tsx:21]: I think of `value` as what would be included in a form request, which is always a string. A number could also work, but I'm not convinced we need to do that.

This would be a breaking change, but I'm not sure if it would actually break anything.

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx (hunk 5 above)
Comment (bobular) [reply packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:652]: You mean it gets lost because it's the same colour and position as the "too many proteins" message that was almost certainly there just before they filtered?

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx (hunk 3 above)
Comment (bobular) [reply packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:412]: Yes, I think so.

`sortRows()` returns the protein table rows in tree leaf order. Proteins that are missing from the tree are an obvious problem. But the tree can also be bigger (more leaves) than the protein table (though Rich says it won't happen) - it's best to play on the safe side.

Just using `mesaRows.length !== leaves?.length` won't protect against a protein table of X rows and a tree with X leaves, but where none of the proteins/leaves match each other.

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx (hunk 5 above)
Comment (bobular) [reply packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx]: I'm not going to tackle this tonight. I don't really see it as a problem, personally. But we can discuss tomorrow.

File: packages/libs/coreui/src/components/inputs/SelectList.tsx (hunk 1 above)
Comment (bobular) [reply packages/libs/coreui/src/components/inputs/SelectList.tsx]: I've fixed it as you suggested. If it's a breaking change, it hasn't broken anything within this repo at least!

**Comment by bobular** [comment]
I'd be grateful if you could have a quick look at the latest changes, @dmfalke - thanks!

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx (hunk 5 above)
Comment (dmfalke) [reply packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx]: > You mean it gets lost because it's the same colour and position as the "too many proteins" message that was almost certainly there just before they filtered?

Yes, that was my thinking. Let's leave it as-is and see if others raise it as an issue.

File: packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx [hunk 6]
```diff
@@ -98,7 +98,10 @@ export function RecordTable_Sequences(
   const numSequences = mesaRows.length;
 
   const treeResponse = useOrthoService(
-    (orthoService) => orthoService.getGroupTree(groupName),
+    (orthoService) => {
+      if (numSequences < 3) return Promise.resolve(undefined);
```
Comment (dmfalke) [inline packages/sites/ortho-site/webapp/wdkCustomization/js/client/records/Sequences.tsx:102]: Should probably use `MIN_SEQUENCES_FOR_TREE` here.
