### PR TITLE
Fix user dataset subsetting distribution OOM

### LINKED ISSUE #1391: Edge case single row UD with large integer causes OOM
The front end is causing a back end OOM when a variable like this

```
{
	"distributionDefaults": {
		"rangeMin": 101,
		"rangeMax": 101,
		"binWidth": 1
	}
}
```

Gets sent to the EDA back end `distribution` endpoint with the following bin spec:

```
{
	"binSpec": {
		"binWidth": 1,
		"displayRangeMax": 101,
		"displayRangeMin": 0
	},
	"filters": [],
	"valueSpec": "count"
}
```

If the max is a large number, then the back end creates a large number of bins and that can OOM.

Clearly the zero `displayRangeMin` is a problem. We could also guard against this on the back end? (New ticket if so, please!)

A simple test case is a user dataset with the following data file:

```
SampleID	Name	Age	Weight
Bobby001	Bob	101	123
```

### PR DESCRIPTION
**Pull request by bobular**
FIxes #1391

### CODE REVIEW

File: packages/libs/eda/src/lib/core/utils/default-axis-range.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ export function numberDateDefaultAxisRange(
             min:
               logScale &&
               observedMin != null &&
-              (observedMin <= 0 ||
+              ((observedMin as number) <= 0 ||
```
Comment (bobular) [inline packages/libs/eda/src/lib/core/utils/default-axis-range.ts:27]: This was just a tidy-up. My IDE is on a higher version of TypeScript, and it didn't like it.

**Review by aurreco-uga — APPROVED** [review]
sorry i dont have time to test so ill approve and we can test in main.
