### PR TITLE
Prevent numerator/denominator checkbox confusion by replacing unstable empty array reference literals

### LINKED ISSUE #1160: EDA - lineplot numerator/denominator checkboxes get reset if you work very fast
To reproduce

* qa.clinepidb.org
* EDA
* any study
* make a lineplot
* choose x
* choose categorical y variable
* AS QUICK AS YOU CAN go and click a numerator checkbox
* you should see your checkbox be reset to unchecked

This appears to be due to the `visConfig` coming back from the user database after a PATCH update. You may not see it on faster connections?

The useEffect in `packages/libs/coreui/src/components/inputs/SelectList.tsx` is presumably resetting the local state of the component because `vizConfig.numeratorValues` has changed (even though it has actually not changed from an empty array to an empty array?)  Is there a rogue `[]`? Yes there is. Fix to follow

### PR DESCRIPTION
**Pull request by bobular**
Fixes #1160 

Fairly simple fix!

### CODE REVIEW

File: packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx [hunk 1]
```diff
@@ -2797,7 +2799,7 @@ export function AggregationInputs<F extends string, P extends Array<string>>(
   props: AggregationConfig<F, P>
 ) {
   const classes = useInputStyles();
-
+  console.log(props);
```
Comment (chowington) [inline packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx:2802]: Can you undo this change, please? Thanks!

**Review by chowington — APPROVED** [review]
Looks good after taking care of a leftover console log!

File: packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx (hunk 1 above)
Comment (bobular) [reply packages/libs/eda/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx:2802]: Oops - yes of course. Thanks for spotting!
